### ISSUE TITLE
Order admin view HAHAHAHAHAHAHA

### ISSUE THREAD

**Issue by Kallzor** [Leohemmingsson/D0018E#66]
## Task description
When you're an admin you'd want to see all the orders

## When is the issue done
When it looks ish ok, it is possible to navigate through the admin pages.

## How is it tested
Manually, making sure nothing is broken. 

## TODO
* [x] Steal html
* [ ] display all orders

**Comment by Leohemmingsson** [comment]
OOOOOO SOPA
